/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.android.ai.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFFC6FF00)
val onPrimaryLight = Color(0xFF283300)
val primaryContainerLight = Color(0xFF4F6600)
val onPrimaryContainerLight = Color(0xFFC6FF00)
val secondaryLight = Color(0xFF34A853)
val onSecondaryLight = Color(0xFF002108)
val secondaryContainerLight = Color(0xFF184E26)
val onSecondaryContainerLight = Color(0xFF3CC360)
val tertiaryLight = Color(0xFFFDADEE)
val onTertiaryLight = Color(0xFF6D2F67)
val tertiaryContainerLight = Color(0xFF7B3A73)
val onTertiaryContainerLight = Color(0xFFFFD7F4)
val errorLight = Color(0xFFFFB4AB)
val onErrorLight = Color(0xFF690005)
val errorContainerLight = Color(0xFFBA1A1A)
val onErrorContainerLight = Color(0xFFFFDAD6)
val backgroundLight = Color(0xFF12140D)
val onBackgroundLight = Color(0xFFE3E3D7)
val surfaceLight = Color(0xFF1D181E)
val onSurfaceLight = Color(0xFFF1F1F1)
val surfaceVariantLight = Color(0xFF3F4948)
val onSurfaceVariantLight = Color(0xFFE5E2E1)
val outlineLight = Color(0xFF7D7171)
val outlineVariantLight = Color(0xFF43454B)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFFEFDFE1)
val inverseOnSurfaceLight = Color(0xFF372E30)
val inversePrimaryLight = Color(0xFF638000)
val surfaceDimLight = Color(0xFF1C1B1B)
val surfaceBrightLight = Color(0xFF3C3B3B)
val surfaceContainerLowestLight = Color(0xFF111111)
val surfaceContainerLowLight = Color(0xFF1C1B1B)
val surfaceContainerLight = Color(0xFF262625)
val surfaceContainerHighLight = Color(0xFF313030)
val surfaceContainerHighestLight = Color(0xFF3C3B3B)

val primaryLightMediumContrast = Color(0xFFC6FF00)
val onPrimaryLightMediumContrast = Color(0xFF1E2A00)
val primaryContainerLightMediumContrast = Color(0xFF4F6600)
val onPrimaryContainerLightMediumContrast = Color(0xFF9ECC00)
val secondaryLightMediumContrast = Color(0xFF34A853)
val onSecondaryLightMediumContrast = Color(0xFF002D0E)
val secondaryContainerLightMediumContrast = Color(0xFF689D6D)
val onSecondaryContainerLightMediumContrast = Color(0xFF63CF80)
val tertiaryLightMediumContrast = Color(0xFFFFEBF7)
val onTertiaryLightMediumContrast = Color(0xFFA45F9A)
val tertiaryContainerLightMediumContrast = Color(0xFFB87EAD)
val onTertiaryContainerLightMediumContrast = Color(0xFF000000)
val errorLightMediumContrast = Color(0xFFFFD2CC)
val onErrorLightMediumContrast = Color(0xFF540003)
val errorContainerLightMediumContrast = Color(0xFFFF5449)
val onErrorContainerLightMediumContrast = Color(0xFF000000)
val backgroundLightMediumContrast = Color(0xFF12140D)
val onBackgroundLightMediumContrast = Color(0xFFE3E3D7)
val surfaceLightMediumContrast = Color(0xFF43454B)
val onSurfaceLightMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantLightMediumContrast = Color(0xFF3F4948)
val onSurfaceVariantLightMediumContrast = Color(0xFFD4DEDD)
val outlineLightMediumContrast = Color(0xFFAAB4B3)
val outlineVariantLightMediumContrast = Color(0xFF889291)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFFEFDFE1)
val inverseOnSurfaceLightMediumContrast = Color(0xFF31282A)
val inversePrimaryLightMediumContrast = Color(0xFF3D4E0F)
val surfaceDimLightMediumContrast = Color(0xFF191113)
val surfaceBrightLightMediumContrast = Color(0xFF4C4244)
val surfaceContainerLowestLightMediumContrast = Color(0xFF0C0607)
val surfaceContainerLowLightMediumContrast = Color(0xFF241B1E)
val surfaceContainerLightMediumContrast = Color(0xFF2F2628)
val surfaceContainerHighLightMediumContrast = Color(0xFF3A3032)
val surfaceContainerHighestLightMediumContrast = Color(0xFF453B3D)

val primaryLightHighContrast = Color(0xFFE3F9A8)
val onPrimaryLightHighContrast = Color(0xFF000000)
val primaryContainerLightHighContrast = Color(0xFF4F6600)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF63CF80)
val onSecondaryLightHighContrast = Color(0xFF000000)
val secondaryContainerLightHighContrast = Color(0xFF184E26)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFFFFD7F4)
val onTertiaryLightHighContrast = Color(0xFF260025)
val tertiaryContainerLightHighContrast = Color(0xFFEEAFE1)
val onTertiaryContainerLightHighContrast = Color(0xFF1D001B)
val errorLightHighContrast = Color(0xFFFFECE9)
val onErrorLightHighContrast = Color(0xFF000000)
val errorContainerLightHighContrast = Color(0xFFFFAEA4)
val onErrorContainerLightHighContrast = Color(0xFF220001)
val backgroundLightHighContrast = Color(0xFF12140D)
val onBackgroundLightHighContrast = Color(0xFFE3E3D7)
val surfaceLightHighContrast = Color(0xFF0F1013)
val onSurfaceLightHighContrast = Color(0xFFFFFFFF)
val surfaceVariantLightHighContrast = Color(0xFF3F4948)
val onSurfaceVariantLightHighContrast = Color(0xFFFFFFFF)
val outlineLightHighContrast = Color(0xFFE8F2F1)
val outlineVariantLightHighContrast = Color(0xFFBAC5C3)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFFEFDFE1)
val inverseOnSurfaceLightHighContrast = Color(0xFF000000)
val inversePrimaryLightHighContrast = Color(0xFF3D4E0F)
val surfaceDimLightHighContrast = Color(0xFF191113)
val surfaceBrightLightHighContrast = Color(0xFF584D50)
val surfaceContainerLowestLightHighContrast = Color(0xFF000000)
val surfaceContainerLowLightHighContrast = Color(0xFF261D20)
val surfaceContainerLightHighContrast = Color(0xFF372E30)
val surfaceContainerHighLightHighContrast = Color(0xFF43393B)
val surfaceContainerHighestLightHighContrast = Color(0xFF4F4446)

val primaryDark = Color(0xFFC6FF00)
val onPrimaryDark = Color(0xFF283300)
val primaryContainerDark = Color(0xFF4F6600)
val onPrimaryContainerDark = Color(0xFFC6FF00)
val secondaryDark = Color(0xFF34A853)
val onSecondaryDark = Color(0xFF002108)
val secondaryContainerDark = Color(0xFF184E26)
val onSecondaryContainerDark = Color(0xFF3CC360)
val tertiaryDark = Color(0xFFFDADEE)
val onTertiaryDark = Color(0xFF6D2F67)
val tertiaryContainerDark = Color(0xFF7B3A73)
val onTertiaryContainerDark = Color(0xFFFFD7F4)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFFBA1A1A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF12140D)
val onBackgroundDark = Color(0xFFE3E3D7)
val surfaceDark = Color(0xFF1D181E)
val onSurfaceDark = Color(0xFFF1F1F1)
val surfaceVariantDark = Color(0xFF3F4948)
val onSurfaceVariantDark = Color(0xFFE5E2E1)
val outlineDark = Color(0xFF7D7171)
val outlineVariantDark = Color(0xFF43454B)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEFDFE1)
val inverseOnSurfaceDark = Color(0xFF372E30)
val inversePrimaryDark = Color(0xFF638000)
val surfaceDimDark = Color(0xFF1C1B1B)
val surfaceBrightDark = Color(0xFF3C3B3B)
val surfaceContainerLowestDark = Color(0xFF111111)
val surfaceContainerLowDark = Color(0xFF1C1B1B)
val surfaceContainerDark = Color(0xFF262625)
val surfaceContainerHighDark = Color(0xFF313030)
val surfaceContainerHighestDark = Color(0xFF3C3B3B)

val primaryDarkMediumContrast = Color(0xFFC6FF00)
val onPrimaryDarkMediumContrast = Color(0xFF1E2A00)
val primaryContainerDarkMediumContrast = Color(0xFF4F6600)
val onPrimaryContainerDarkMediumContrast = Color(0xFF9ECC00)
val secondaryDarkMediumContrast = Color(0xFF34A853)
val onSecondaryDarkMediumContrast = Color(0xFF002D0E)
val secondaryContainerDarkMediumContrast = Color(0xFF689D6D)
val onSecondaryContainerDarkMediumContrast = Color(0xFF63CF80)
val tertiaryDarkMediumContrast = Color(0xFFFFEBF7)
val onTertiaryDarkMediumContrast = Color(0xFFA45F9A)
val tertiaryContainerDarkMediumContrast = Color(0xFFB87EAD)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF12140D)
val onBackgroundDarkMediumContrast = Color(0xFFE3E3D7)
val surfaceDarkMediumContrast = Color(0xFF43454B)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF3F4948)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD4DEDD)
val outlineDarkMediumContrast = Color(0xFFAAB4B3)
val outlineVariantDarkMediumContrast = Color(0xFF889291)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFEFDFE1)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF31282A)
val inversePrimaryDarkMediumContrast = Color(0xFF3D4E0F)
val surfaceDimDarkMediumContrast = Color(0xFF191113)
val surfaceBrightDarkMediumContrast = Color(0xFF4C4244)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF0C0607)
val surfaceContainerLowDarkMediumContrast = Color(0xFF241B1E)
val surfaceContainerDarkMediumContrast = Color(0xFF2F2628)
val surfaceContainerHighDarkMediumContrast = Color(0xFF3A3032)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF453B3D)

val primaryDarkHighContrast = Color(0xFFE3F9A8)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF4F6600)
val onPrimaryContainerDarkHighContrast = Color(0xFFFFFFFF)
val secondaryDarkHighContrast = Color(0xFF63CF80)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFF184E26)
val onSecondaryContainerDarkHighContrast = Color(0xFFFFFFFF)
val tertiaryDarkHighContrast = Color(0xFFFFD7F4)
val onTertiaryDarkHighContrast = Color(0xFF260025)
val tertiaryContainerDarkHighContrast = Color(0xFFEEAFE1)
val onTertiaryContainerDarkHighContrast = Color(0xFF1D001B)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF12140D)
val onBackgroundDarkHighContrast = Color(0xFFE3E3D7)
val surfaceDarkHighContrast = Color(0xFF0F1013)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF3F4948)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFE8F2F1)
val outlineVariantDarkHighContrast = Color(0xFFBAC5C3)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFEFDFE1)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF3D4E0F)
val surfaceDimDarkHighContrast = Color(0xFF191113)
val surfaceBrightDarkHighContrast = Color(0xFF584D50)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF261D20)
val surfaceContainerDarkHighContrast = Color(0xFF372E30)
val surfaceContainerHighDarkHighContrast = Color(0xFF43393B)
val surfaceContainerHighestDarkHighContrast = Color(0xFF4F4446)

val geminiNano = Color(0xFFDCE2FF)
val geminiProFlash = Color(0xFFC7E4FF)
val imagen = Color(0xFF2DAEB8)
val firebase = Color(0xFFFFC400)
val media3 = Color(0xFF80DA88)
val mlKit = Color(0xFFC2E7FF)

val startGradient = Color(0x99000000)
